### ISSUE TITLE
Show profile page in mode according to user log in

### ISSUE THREAD

**Issue by ElleTojaroon** [krtejeda/CodeU-Spring-2018#25]
Profile page has 2 mode: owner and visitor. Show the page according to the user that logged in. Show visitor mode if no user is logged in.

Blocked by #24

**Comment by ElleTojaroon** [comment]
sorry @mynguyenbmc , this story was actually closely related to #24 . So I finished it. There're many more you can pick from the sprint. Let me know if you have any question.

**Comment by mynguyenbmc** [comment]
@ElleTojaroon Thanks, Elle! I'm working on the async!
