### ISSUE TITLE
After logged in, go back to the same url

### ISSUE THREAD

**Issue by ElleTojaroon** [krtejeda/CodeU-Spring-2018#34]
Right now, after logging in, it leads to the /conversations page. Edit so that it leads to the url user was at before logging in.

**Comment by mynguyenbmc** [comment]
Sending user to the previous url may lead to potential security problem I think? Can we lead user to the activity feed instead?

**Comment by ElleTojaroon** [comment]
What use case that would you say problematic? On pages that require users to log in first, we check and sends the user to log in page if they're not.
