### ISSUE TITLE
Add forget password feature

### ISSUE THREAD

**Issue by ElleTojaroon** [krtejeda/CodeU-Spring-2018#35]
Blocked by #37  , which is adding UpdatePersistentDatastore.java for the edit description feature. This story will be able to utilize the class to update password.

**Comment by mynguyenbmc** [comment]
@ElleTojaroon I like this!! One question though: How can we verify that the person requesting new password is the actual user? Normally we would have verification methods such as email addresses or phone numbers right. Should we add something like a security question?

**Comment by ElleTojaroon** [comment]
oh I haven't thought about that yet. Good question! Maybe you can find a solution that is easy to implement. But we can just do it without verifying as a first step.
