### ISSUE TITLE
Configure github repository

### ISSUE THREAD

**Issue by krugg-codeu** [krtejeda/CodeU-Spring-2018#5]
Create the github repository and share it with all team members.

Potentially configure the repository to require code reviews. This seems worth doing, especially as one focus of CodeU is to practice developing as a team with peer code reviews.
Visit your repository > Settings > Branches.
In protected branches, select the master branch. Check:
  - Protect this branch.
  - Require pull request reviews before merging
  - Dismiss stale pull request approvals when new commits are pushed
  - Require status checks to pass before merging
  - Require branches to be up to date before merging
  - Include administrators
  - Save Changes

Potentially configure the repository to do continuous integration.  Automatically build code and run tests and block the pull request if they don't pass.  This is similar to how submissions are done at Google and is probably worth trying to see how well it works.  This may need a bit of investigation to see how to configure and troubleshoot if anything goes wrong.  One CodeU Project Advisor said they thought it was very easy to setup though:  "Travis CI needs a config file “.travis.yml” in the project root with a single line of “language: java”; once that’s there, everything should work automatically (see https://github.com/gssafar/codeu_project_2018/blob/master/.travis.yml)"

**Comment by krtejeda** [comment]
Configured repository to require code reviews and added file which will (hopefully) configure continuous integration
